function [varMin,varMax] = standardvariables(con,n,varMin,varMax)
%% Standardised variables to be held constant during optimisation

% variCons = {"Variables",    "Num Of",   "Conditions"    'Transformations';...
%     "Dihedral",             "~",        "~",            '~';...
%     "Chord",                n+1,        "< Previous",   '.*AftLength';...
%     "LESweep",              n,          "~"             '~';...
%     "Semispan",             n,          "Minimum 0.5",  '~';...            
%     "Section",              n+1,        "Floor",        '~';...
%     "xOffset",              "~",        "~",            '.*AftLength';...
%     "zOffset",              "~",        "~"             '.*AftHeight/2';...
%     "UpperLength",          "~",        "~",            '~';...
%     "yUpperRad",            "~",        "~",            '~';...
%     "yBotRatio",            "~",        "~",            '~';...
%     "zUpperRad",            "~",        "~",            '~';...
%     "SideLength",           "~",        "~",            '~';...
%     "zLowerRad",            "~",        "~",            '~';...
%     "AftLength",            "~",        "~",            '~';...
%     "NoseRad",              "~",        "~",            '~';...
%     "NoseLength",           "~",        "~",            '.*NoseRad';...
%     "zNoseOffset",          "~",        "~",            '.*AftHeight/2';...
%     "ForeLength",           "~",        "~",            '~'};

stanChord = repmat(0.8,1,n+1);
stanLESweep = repmat(40,1,n);
stanSemispan = [2, repmat(1,1,n-1)];
stanSection = repmat(2,1,n+1);

% As above
standardVar = [0, stanChord, stanLESweep, stanSemispan, stanSection, 0,0,... % Wing
    0,1,1, 1,0,1, 8, 0.25,0.25,0, 4]; % Body

varMin(con) = standardVar(con);
varMax(con) = standardVar(con);